//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DB", "PredmetiStudenti", "Predmeti", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Vjezba_11_C_sharp_baze_podataka.Predmeti), "Studenti", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Vjezba_11_C_sharp_baze_podataka.Studenti))]

#endregion

namespace Vjezba_11_C_sharp_baze_podataka
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StudentiEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StudentiEntities object using the connection string found in the 'StudentiEntities' section of the application configuration file.
        /// </summary>
        public StudentiEntities() : base("name=StudentiEntities", "StudentiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StudentiEntities object.
        /// </summary>
        public StudentiEntities(string connectionString) : base(connectionString, "StudentiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StudentiEntities object.
        /// </summary>
        public StudentiEntities(EntityConnection connection) : base(connection, "StudentiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Predmeti> Predmeti
        {
            get
            {
                if ((_Predmeti == null))
                {
                    _Predmeti = base.CreateObjectSet<Predmeti>("Predmeti");
                }
                return _Predmeti;
            }
        }
        private ObjectSet<Predmeti> _Predmeti;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Studenti> Studenti
        {
            get
            {
                if ((_Studenti == null))
                {
                    _Studenti = base.CreateObjectSet<Studenti>("Studenti");
                }
                return _Studenti;
            }
        }
        private ObjectSet<Studenti> _Studenti;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Predmeti EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPredmeti(Predmeti predmeti)
        {
            base.AddObject("Predmeti", predmeti);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Studenti EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudenti(Studenti studenti)
        {
            base.AddObject("Studenti", studenti);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB", Name="Predmeti")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Predmeti : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Predmeti object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="naziv">Initial value of the Naziv property.</param>
        public static Predmeti CreatePredmeti(global::System.Int32 id, global::System.String naziv)
        {
            Predmeti predmeti = new Predmeti();
            predmeti.Id = id;
            predmeti.Naziv = naziv;
            return predmeti;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Naziv
        {
            get
            {
                return _Naziv;
            }
            set
            {
                OnNazivChanging(value);
                ReportPropertyChanging("Naziv");
                _Naziv = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Naziv");
                OnNazivChanged();
            }
        }
        private global::System.String _Naziv;
        partial void OnNazivChanging(global::System.String value);
        partial void OnNazivChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB", "PredmetiStudenti", "Studenti")]
        public EntityCollection<Studenti> Studenti
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Studenti>("DB.PredmetiStudenti", "Studenti");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Studenti>("DB.PredmetiStudenti", "Studenti", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB", Name="Studenti")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Studenti : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Studenti object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="ime">Initial value of the Ime property.</param>
        /// <param name="prezime">Initial value of the Prezime property.</param>
        public static Studenti CreateStudenti(global::System.Int32 id, global::System.String ime, global::System.String prezime)
        {
            Studenti studenti = new Studenti();
            studenti.Id = id;
            studenti.Ime = ime;
            studenti.Prezime = prezime;
            return studenti;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ime
        {
            get
            {
                return _Ime;
            }
            set
            {
                OnImeChanging(value);
                ReportPropertyChanging("Ime");
                _Ime = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ime");
                OnImeChanged();
            }
        }
        private global::System.String _Ime;
        partial void OnImeChanging(global::System.String value);
        partial void OnImeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Prezime
        {
            get
            {
                return _Prezime;
            }
            set
            {
                OnPrezimeChanging(value);
                ReportPropertyChanging("Prezime");
                _Prezime = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Prezime");
                OnPrezimeChanged();
            }
        }
        private global::System.String _Prezime;
        partial void OnPrezimeChanging(global::System.String value);
        partial void OnPrezimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB", "PredmetiStudenti", "Predmeti")]
        public EntityCollection<Predmeti> Predmeti
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Predmeti>("DB.PredmetiStudenti", "Predmeti");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Predmeti>("DB.PredmetiStudenti", "Predmeti", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
